name: Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - nodejs-app/Chart.yaml
      - .github/workflows/deploy.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Write KUBECONFIG file
      run: echo ${{ secrets.KUBECONFIG }} > ~/.kube/config

    - name: Deploy helmchart1
      run: helm install nodejs ./nodejs-app