name: Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - nodejs-app/Chart.yaml
env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy helmchart
      run: helm install nodejs ./nodejs-app